// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: user.transport.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransportClient is the client API for Transport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransportClient interface {
	FindUsers(ctx context.Context, in *FindUsersRequest, opts ...grpc.CallOption) (*FindUsersReply, error)
	SaveUsers(ctx context.Context, in *SaveUsersRequest, opts ...grpc.CallOption) (*SaveUsersReply, error)
	RemoveUsers(ctx context.Context, in *RemoveUsersRequest, opts ...grpc.CallOption) (*RemoveUsersReply, error)
}

type transportClient struct {
	cc grpc.ClientConnInterface
}

func NewTransportClient(cc grpc.ClientConnInterface) TransportClient {
	return &transportClient{cc}
}

func (c *transportClient) FindUsers(ctx context.Context, in *FindUsersRequest, opts ...grpc.CallOption) (*FindUsersReply, error) {
	out := new(FindUsersReply)
	err := c.cc.Invoke(ctx, "/demo01.service.v1.Transport/FindUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportClient) SaveUsers(ctx context.Context, in *SaveUsersRequest, opts ...grpc.CallOption) (*SaveUsersReply, error) {
	out := new(SaveUsersReply)
	err := c.cc.Invoke(ctx, "/demo01.service.v1.Transport/SaveUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportClient) RemoveUsers(ctx context.Context, in *RemoveUsersRequest, opts ...grpc.CallOption) (*RemoveUsersReply, error) {
	out := new(RemoveUsersReply)
	err := c.cc.Invoke(ctx, "/demo01.service.v1.Transport/RemoveUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransportServer is the server API for Transport service.
// All implementations must embed UnimplementedTransportServer
// for forward compatibility
type TransportServer interface {
	FindUsers(context.Context, *FindUsersRequest) (*FindUsersReply, error)
	SaveUsers(context.Context, *SaveUsersRequest) (*SaveUsersReply, error)
	RemoveUsers(context.Context, *RemoveUsersRequest) (*RemoveUsersReply, error)
	mustEmbedUnimplementedTransportServer()
}

// UnimplementedTransportServer must be embedded to have forward compatible implementations.
type UnimplementedTransportServer struct {
}

func (UnimplementedTransportServer) FindUsers(context.Context, *FindUsersRequest) (*FindUsersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUsers not implemented")
}
func (UnimplementedTransportServer) SaveUsers(context.Context, *SaveUsersRequest) (*SaveUsersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveUsers not implemented")
}
func (UnimplementedTransportServer) RemoveUsers(context.Context, *RemoveUsersRequest) (*RemoveUsersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUsers not implemented")
}
func (UnimplementedTransportServer) mustEmbedUnimplementedTransportServer() {}

// UnsafeTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransportServer will
// result in compilation errors.
type UnsafeTransportServer interface {
	mustEmbedUnimplementedTransportServer()
}

func RegisterTransportServer(s grpc.ServiceRegistrar, srv TransportServer) {
	s.RegisterService(&Transport_ServiceDesc, srv)
}

func _Transport_FindUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportServer).FindUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo01.service.v1.Transport/FindUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportServer).FindUsers(ctx, req.(*FindUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transport_SaveUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportServer).SaveUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo01.service.v1.Transport/SaveUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportServer).SaveUsers(ctx, req.(*SaveUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transport_RemoveUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportServer).RemoveUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo01.service.v1.Transport/RemoveUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportServer).RemoveUsers(ctx, req.(*RemoveUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Transport_ServiceDesc is the grpc.ServiceDesc for Transport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo01.service.v1.Transport",
	HandlerType: (*TransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindUsers",
			Handler:    _Transport_FindUsers_Handler,
		},
		{
			MethodName: "SaveUsers",
			Handler:    _Transport_SaveUsers_Handler,
		},
		{
			MethodName: "RemoveUsers",
			Handler:    _Transport_RemoveUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.transport.proto",
}
